// Real-world border adjacencies between countries (ISO 3166-1 alpha-2 codes),
// exported 2026-08-15. Each token is one directed source-target link; most
// borders appear in both directions, exactly as the source dataset lists them.
export const COUNTRY_BORDER_LINKS: string =
  'AZ-TR DE-CH GE-TR HR-SI KG-UZ KR-KP MO-CN SN-MR SZ-ZA UA-SK DZ-EH GY-VE HU-UA KW-SA LT-RU MC-FR ' +
  'MR-EH MW-ZM NO-SE SD-SS SM-IT SV-HN TN-LY BE-NL CA-US CZ-SK DK-DE MK-RS QA-SA AL-RS AT-CH CM-NG ' +
  'ER-SD GF-SR GT-MX PL-UA PY-BR SA-YE BO-PE BW-ZW EC-PE GB-IE GH-TG GQ-GA ID-TL LB-SY MM-TH NL-DE ' +
  'SE-NO SL-LR TZ-ZM VN-LA FI-SE KP-RU KZ-UZ LA-VN LS-ZA ME-RS MF-SX NI-HN UY-BR ZM-ZW AF-UZ CG-GA ' +
  'CH-LI CL-PE CN-VN CR-PA GI-ES IL-SY IN-PK MY-TH NE-NG RO-UA RW-UG US-MX AD-ES AM-TR AR-UY BN-MY ' +
  'CF-SD ET-SD HN-NI JO-SY LV-RU SI-IT VA-IT AE-SA AO-ZM BG-TR BY-UA HK-CN IE-GB LI-CH LY-TN MN-RU ' +
  'TD-SD TH-MM UZ-TM BD-MM EG-SD GA-GQ IQ-TR ML-SN NP-IN RS-RO UG-TZ CI-ML EH-MA GM-SN HT-DO MX-US ' +
  'PE-EC PS-JO YE-SA BT-IN BZ-MX CD-ZM GW-SN IR-TM KH-VN MZ-ZW OM-YE TL-ID TM-UZ BF-TG BI-TZ BJ-TG ' +
  'EE-RU FR-CH GR-TR PT-ES SK-UA SO-KE SR-GY TJ-UZ TR-SY VE-GY CO-VE DJ-SO IT-VA LR-SL MA-EH MD-UA ' +
  'NA-ZM NG-NE PG-ID RU-UA SS-UG TG-GH BR-VE DO-HT KE-UG LU-FR PA-CR PK-IR SY-TR ZA-ZW BA-RS ES-PT ' +
  'GN-SL SX-MF ZW-ZM AZ-RU DE-PL GE-RU HR-RS KG-TJ SN-ML SZ-MZ UA-RU DZ-TN GY-SR HU-SI KW-IQ LT-PL ' +
  'MR-SN MW-TZ NO-RU SD-LY SV-GT TN-DZ BE-LU CZ-PL MK-GR AL-MK AT-SI CM-GA ER-ET GF-BR GT-HN PL-SK ' +
  'PY-BO SA-AE BO-PY BW-ZM EC-CO GH-CI GQ-CM ID-PG LB-IL MM-LA NL-BE SE-FI SL-GN TZ-UG VN-CN FI-RU ' +
  'KP-KR KZ-TM LA-TH ME-HR NI-CR UY-AR ZM-TZ AF-TM CG-CD CH-IT CL-BO CN-TJ CR-NI IL-PS IN-NP MY-ID ' +
  'NE-ML RO-RS RW-TZ US-CA AD-FR AM-IR AR-PY CF-SS ET-SS HN-GT JO-SA LV-LT SI-HU AE-OM AO-NA BG-RS ' +
  'BY-RU LI-AT LY-SD MN-CN TD-NG TH-MY UZ-TJ BD-IN EG-PS GA-CG IQ-SY ML-NE NP-CN RS-MK UG-SS CI-LR ' +
  'EH-MR MX-GT PE-CO PS-IL YE-OM BT-CN BZ-GT CD-UG GW-GN IR-TR KH-TH MZ-ZM OM-SA TM-KZ BF-NE BI-RW ' +
  'BJ-NG EE-LV FR-ES GR-MK SK-PL SO-ET SR-GF TJ-KG TR-IQ VE-CO CO-PE DJ-ET IT-CH LR-GN MA-ES MD-RO ' +
  'NA-ZA NG-TD RU-PL SS-SD TG-BF BR-UY KE-TZ LU-DE PA-CO PK-IN SY-LB ZA-SZ BA-ME ES-MA GN-SN ZW-ZA ' +
  'AZ-IR DE-NL GE-AZ HR-ME KG-KZ SN-GW UA-RO DZ-NE GY-BR HU-SK LT-LV MR-ML MW-MZ NO-FI SD-ER BE-DE ' +
  'CZ-DE MK-BG AL-ME AT-SK CM-GQ ER-DJ GT-SV PL-RU PY-AR SA-QA BO-CL BW-ZA GH-BF ID-MY MM-IN TZ-RW ' +
  'VN-KH FI-NO KP-CN KZ-RU LA-MM ME-BA ZM-NA AF-TJ CG-CF CH-DE CL-AR CN-RU IL-LB IN-MM MY-BN NE-LY ' +
  'RO-MD RW-CD AM-GE AR-CL CF-CD ET-SO HN-SV JO-PS LV-EE SI-HR AO-CD BG-RO BY-PL LY-NE TD-NE TH-LA ' +
  'UZ-KG EG-LY GA-CM IQ-SA ML-MR RS-ME UG-RW CI-GN EH-DZ MX-BZ PE-CL PS-EG CD-TZ IR-PK KH-LA MZ-TZ ' +
  'OM-AE TM-IR BF-ML BI-CD BJ-NE FR-MC GR-BG SK-HU SO-DJ SR-BR TJ-CN TR-IR VE-BR CO-PA DJ-ER IT-SI ' +
  'LR-CI MA-DZ NA-BW NG-CM RU-NO SS-KE TG-BJ BR-SR KE-SS LU-BE PK-CN SY-JO ZA-NA BA-HR ES-GI GN-ML ' +
  'ZW-MZ AZ-GE DE-LU GE-AM HR-HU KG-CN SN-GN UA-PL DZ-MA HU-RS LT-BY MR-DZ SD-ET BE-FR CZ-AT MK-AL ' +
  'AL-GR AT-LI CM-CG GT-BZ PL-LT SA-OM BO-BR BW-NA MM-CN TZ-MZ KZ-KG LA-KH ME-AL ZM-MZ AF-PK CG-CM ' +
  'CH-FR CN-PK IL-JO IN-CN NE-TD RO-HU RW-BI AM-AZ AR-BR CF-CG ET-KE JO-IL LV-BY SI-AT AO-CG BG-MK ' +
  'BY-LT LY-EG TD-LY TH-KH UZ-KZ EG-IL IQ-KW ML-GN RS-HU UG-KE CI-GH PE-BR CD-SS IR-IQ MZ-ZA TM-AF ' +
  'BF-GH BJ-BF FR-LU GR-AL SK-CZ TJ-AF TR-GR CO-EC IT-SM NA-AO NG-BJ RU-MN SS-ET BR-PE KE-SO PK-AF ' +
  'SY-IL ZA-MZ ES-FR GN-LR ZW-BW AZ-AM DE-FR HR-BA SN-GM UA-MD DZ-MR HU-RO SD-EG AT-IT CM-TD PL-DE ' +
  'SA-KW BO-AR MM-BD TZ-MW KZ-CN LA-CN ZM-MW AF-IR CG-AO CH-AT CN-NP IL-EG IN-BT NE-BF RO-BG AR-BO ' +
  'CF-TD ET-ER JO-IQ BG-GR BY-LV LY-TD TD-CF UZ-AF IQ-JO ML-CI RS-HR UG-CD CI-BF PE-BO CD-RW IR-AZ ' +
  'MZ-SZ BF-CI FR-IT SK-AT TR-GE CO-BR IT-FR RU-LT SS-CD BR-PY KE-ET SY-IQ ZA-LS ES-AD GN-GW DE-DK ' +
  'UA-HU DZ-ML HU-HR SD-TD AT-HU CM-CF PL-CZ SA-JO TZ-KE ZM-CD AF-CN CN-MM IN-BD NE-BJ CF-CM ET-DJ ' +
  'LY-DZ TD-CM IQ-IR ML-BF RS-BG CD-CG IR-AM MZ-MW BF-BJ FR-DE TR-BG IT-AT RU-LV SS-CF BR-GY ZA-BW ' +
  'GN-CI DE-CZ UA-BY DZ-LY HU-AT SD-CF AT-DE PL-BY SA-IQ TZ-CD ZM-BW CN-MN NE-DZ ML-DZ RS-BA CD-CF ' +
  'IR-AF FR-BE TR-AZ RU-KP BR-GF DE-BE AT-CZ TZ-BI ZM-AO CN-MO RS-AL CD-BI FR-AD TR-AM RU-KZ BR-CO ' +
  'DE-AT CN-LA CD-AO RU-GE BR-BO CN-KG RU-FI BR-AR CN-KP RU-EE CN-KZ RU-CN CN-IN RU-BY CN-HK RU-AZ ' +
  'CN-BT CN-AF'
